baseURL = 'https://example.org/'
title = 'My New Hugo Site'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 2
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1

[menu]
[[menu.main]]
identifier = 'home'
pageRef = '/'
weight = 1
[[menu.main]]
identifier = 'subpage'
pageRef = 'subpage'
weight = 2
